---

- name: Lab1 - Create a vs
  hosts: all
  connection: local
  tasks:
     - name: Create pool using bigip_pool module
       bigip_pool:
          server: "{{ inventory_hostname }}"
          user: admin
          password: admin
          validate_certs: no
          name: workshop_pool
          lb_method: ratio-member
       delegate_to: localhost
       
     - name: Create vs using bigip_virtual_server module
       bigip_virtual_server:
          server: "{{ inventory_hostname }}"
          user: admin
          password: admin
          validate_certs: no
          name: ansible
          partition: workshop
          destination: 192.168.5.11
          snat: Automap
          port: 80
       delegate_to: localhost
       
      


