---

- name: Lab1 - Create a vs
  hosts: all
  connection: local
  tasks:
     - name: Create vs using bigip_virtual_server module
        
       bigip_virtual_server:
          server: "{ inventory_hostname }}"
          user: admin
          password: admin
          validate_certs: no
          name: "ansible_test"
          destination: "192.168.5.10"
          snat: "Automap"
          port: "80"
       delegate_to: localhost
