---

- name: Lab1 - Create a vs
  hosts: all
  connection: local
  tasks:
     - name: Create pool using bigip_pool module
       bigip_pool:
          server: "{{ inventory_hostname }}"
          user: admin
          password: admin
          validate_certs: no
          name: navy_pool
          lb_method: observed-node
       delegate_to: localhost
       
     - name: Create vs using bigip_virtual_server module
       bigip_virtual_server:
          server: "{{ inventory_hostname }}"
          user: admin
          password: admin
          validate_certs: no
          name: ansible
          partition: NAVY
          destination: 192.168.5.10
          snat: None
          port: 80
       delegate_to: localhost
      

