---

- name: Lab2
  hosts: all
  connection: local
  tasks:
    - name: Create VS using 2.5 module
      bigip_virtual_server:
        server: lb.mydomain.net
        user: admin
        password: admin
        state: present
        partition: VA
        name: my-virtual-server
        destination: 10.10.10.10
        port: 443
        pool: my-pool
        snat: Automap
        description: Test Virtual Server
        enabled_vlans:
          - /Common/vlan2
      delegate_to: localhost
