---

- name: Lab 3 - Create UCS backup
  hosts: all
  connection: local
  tasks:
     - name: Create UCS backup
       bigip_ucs_fetch:
          user: admin
          password: admin
          backup: yes
          server: "{{ inventory_hostname }}"
          validate_certs: no
          src: cs_backup.ucs
          dest: /tmp/cs_backup.ucs
       delegate_to: localhost

