---

- name: Lab 3 - Create UCS backup
  hosts: all
  connection: local
  tasks:
     - name: Create UCS backup
       bigip_ucs:
          user: admin
          password: admin
          server: "{{ inventory_hostname }}"
          validate_certs: no
          state: present
          ucs: /tmp/bigip.localhost.localdomain.ucs
       delegate_to: localhost

