---

- name: Install latest HTTP iApp template 
  hosts: all
  connection: local
  gather_facts: no

  vars:
    userName: admin
    password: adminadmin

  tasks:
       - name: Install HTTP iApp
         bigip_iapp_template:
           content: "{{ lookup('file', '../tmp/f5.http.v1.2.0.tmpl') }}"
           user: "{{ userName }}"
           server: "{{ inventory_hostname }}"
           state: present
           password: "{{ password }}"
           validate_certs: no
         delegate_to: localhost


