---

- name: Lab1 - Create a node
  hosts: all
  connection: local
  tasks:
     - name: Create node using bigip_node module and when conditional
       bigip_node:
          server: "{{ inventory_hostname }}"
          user: admin
          password: adminadmin
          validate_certs: no
          address: "10.1.10.100"
          name: "Server1"
          state: "{{ state }}"
       delegate_to: localhost
       when: state == "present"

     - name: Remove node using bigip_node module and when conditional
       bigip_node:
          server: "{{ inventory_hostname }}"
          user: admin
          password: adminadmin
          validate_certs: no
          address: "10.1.10.100"
          name: "Server1"
          state: "{{ state }}"
       delegate_to: localhost
       when: state == "absent"
